/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as PreorderProductsSplatRouteImport } from './routes/preorder-products.$'
import { Route as LocaleTasksRouteImport } from './routes/$locale.tasks'
import { Route as LocaleSignUpRouteImport } from './routes/$locale.sign-up'
import { Route as LocaleSignInRouteImport } from './routes/$locale.sign-in'
import { Route as LocaleServicesRouteImport } from './routes/$locale.services'
import { Route as LocalePreorderRouteImport } from './routes/$locale.preorder'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale.admin.index'
import { Route as LocaleTasksSplatRouteImport } from './routes/$locale.tasks_.$'
import { Route as LocaleSignUpSsoCallbackRouteImport } from './routes/$locale.sign-up_.sso-callback'
import { Route as LocaleSignUpSplatRouteImport } from './routes/$locale.sign-up_.$'
import { Route as LocaleSignInSsoCallbackRouteImport } from './routes/$locale.sign-in_.sso-callback'
import { Route as LocaleAdminServicesRouteImport } from './routes/$locale.admin.services'
import { Route as LocaleAdminProductsRouteImport } from './routes/$locale.admin.products'
import { Route as LocaleAdminPreordersRouteImport } from './routes/$locale.admin.preorders'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const PreorderProductsSplatRoute = PreorderProductsSplatRouteImport.update({
  id: '/preorder-products/$',
  path: '/preorder-products/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTasksRoute = LocaleTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignUpRoute = LocaleSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignInRoute = LocaleSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleServicesRoute = LocaleServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePreorderRoute = LocalePreorderRouteImport.update({
  id: '/preorder',
  path: '/preorder',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleTasksSplatRoute = LocaleTasksSplatRouteImport.update({
  id: '/tasks_/$',
  path: '/tasks/$',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignUpSsoCallbackRoute = LocaleSignUpSsoCallbackRouteImport.update({
  id: '/sign-up_/sso-callback',
  path: '/sign-up/sso-callback',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignUpSplatRoute = LocaleSignUpSplatRouteImport.update({
  id: '/sign-up_/$',
  path: '/sign-up/$',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSignInSsoCallbackRoute = LocaleSignInSsoCallbackRouteImport.update({
  id: '/sign-in_/sso-callback',
  path: '/sign-in/sso-callback',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminServicesRoute = LocaleAdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminProductsRoute = LocaleAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminPreordersRoute = LocaleAdminPreordersRouteImport.update({
  id: '/admin/preorders',
  path: '/admin/preorders',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRoute
  '/$locale/preorder': typeof LocalePreorderRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tasks': typeof LocaleTasksRoute
  '/preorder-products/$': typeof PreorderProductsSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/preorders': typeof LocaleAdminPreordersRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/services': typeof LocaleAdminServicesRoute
  '/$locale/sign-in/sso-callback': typeof LocaleSignInSsoCallbackRoute
  '/$locale/sign-up/$': typeof LocaleSignUpSplatRoute
  '/$locale/sign-up/sso-callback': typeof LocaleSignUpSsoCallbackRoute
  '/$locale/tasks/$': typeof LocaleTasksSplatRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$locale/preorder': typeof LocalePreorderRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tasks': typeof LocaleTasksRoute
  '/preorder-products/$': typeof PreorderProductsSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/preorders': typeof LocaleAdminPreordersRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/services': typeof LocaleAdminServicesRoute
  '/$locale/sign-in/sso-callback': typeof LocaleSignInSsoCallbackRoute
  '/$locale/sign-up/$': typeof LocaleSignUpSplatRoute
  '/$locale/sign-up/sso-callback': typeof LocaleSignUpSsoCallbackRoute
  '/$locale/tasks/$': typeof LocaleTasksSplatRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRoute
  '/$locale/preorder': typeof LocalePreorderRoute
  '/$locale/services': typeof LocaleServicesRoute
  '/$locale/sign-in': typeof LocaleSignInRoute
  '/$locale/sign-up': typeof LocaleSignUpRoute
  '/$locale/tasks': typeof LocaleTasksRoute
  '/preorder-products/$': typeof PreorderProductsSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/preorders': typeof LocaleAdminPreordersRoute
  '/$locale/admin/products': typeof LocaleAdminProductsRoute
  '/$locale/admin/services': typeof LocaleAdminServicesRoute
  '/$locale/sign-in_/sso-callback': typeof LocaleSignInSsoCallbackRoute
  '/$locale/sign-up_/$': typeof LocaleSignUpSplatRoute
  '/$locale/sign-up_/sso-callback': typeof LocaleSignUpSsoCallbackRoute
  '/$locale/tasks_/$': typeof LocaleTasksSplatRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/preorder'
    | '/$locale/services'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tasks'
    | '/preorder-products/$'
    | '/$locale/'
    | '/$locale/admin/preorders'
    | '/$locale/admin/products'
    | '/$locale/admin/services'
    | '/$locale/sign-in/sso-callback'
    | '/$locale/sign-up/$'
    | '/$locale/sign-up/sso-callback'
    | '/$locale/tasks/$'
    | '/$locale/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$locale/preorder'
    | '/$locale/services'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tasks'
    | '/preorder-products/$'
    | '/$locale'
    | '/$locale/admin/preorders'
    | '/$locale/admin/products'
    | '/$locale/admin/services'
    | '/$locale/sign-in/sso-callback'
    | '/$locale/sign-up/$'
    | '/$locale/sign-up/sso-callback'
    | '/$locale/tasks/$'
    | '/$locale/admin'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/preorder'
    | '/$locale/services'
    | '/$locale/sign-in'
    | '/$locale/sign-up'
    | '/$locale/tasks'
    | '/preorder-products/$'
    | '/$locale/'
    | '/$locale/admin/preorders'
    | '/$locale/admin/products'
    | '/$locale/admin/services'
    | '/$locale/sign-in_/sso-callback'
    | '/$locale/sign-up_/$'
    | '/$locale/sign-up_/sso-callback'
    | '/$locale/tasks_/$'
    | '/$locale/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRoute
  PreorderProductsSplatRoute: typeof PreorderProductsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/preorder-products/$': {
      id: '/preorder-products/$'
      path: '/preorder-products/$'
      fullPath: '/preorder-products/$'
      preLoaderRoute: typeof PreorderProductsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/tasks': {
      id: '/$locale/tasks'
      path: '/tasks'
      fullPath: '/$locale/tasks'
      preLoaderRoute: typeof LocaleTasksRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-up': {
      id: '/$locale/sign-up'
      path: '/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleSignUpRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-in': {
      id: '/$locale/sign-in'
      path: '/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleSignInRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/services': {
      id: '/$locale/services'
      path: '/services'
      fullPath: '/$locale/services'
      preLoaderRoute: typeof LocaleServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/preorder': {
      id: '/$locale/preorder'
      path: '/preorder'
      fullPath: '/$locale/preorder'
      preLoaderRoute: typeof LocalePreorderRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/tasks_/$': {
      id: '/$locale/tasks_/$'
      path: '/tasks/$'
      fullPath: '/$locale/tasks/$'
      preLoaderRoute: typeof LocaleTasksSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-up_/sso-callback': {
      id: '/$locale/sign-up_/sso-callback'
      path: '/sign-up/sso-callback'
      fullPath: '/$locale/sign-up/sso-callback'
      preLoaderRoute: typeof LocaleSignUpSsoCallbackRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-up_/$': {
      id: '/$locale/sign-up_/$'
      path: '/sign-up/$'
      fullPath: '/$locale/sign-up/$'
      preLoaderRoute: typeof LocaleSignUpSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/sign-in_/sso-callback': {
      id: '/$locale/sign-in_/sso-callback'
      path: '/sign-in/sso-callback'
      fullPath: '/$locale/sign-in/sso-callback'
      preLoaderRoute: typeof LocaleSignInSsoCallbackRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/services': {
      id: '/$locale/admin/services'
      path: '/admin/services'
      fullPath: '/$locale/admin/services'
      preLoaderRoute: typeof LocaleAdminServicesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/products': {
      id: '/$locale/admin/products'
      path: '/admin/products'
      fullPath: '/$locale/admin/products'
      preLoaderRoute: typeof LocaleAdminProductsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/preorders': {
      id: '/$locale/admin/preorders'
      path: '/admin/preorders'
      fullPath: '/$locale/admin/preorders'
      preLoaderRoute: typeof LocaleAdminPreordersRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocalePreorderRoute: typeof LocalePreorderRoute
  LocaleServicesRoute: typeof LocaleServicesRoute
  LocaleSignInRoute: typeof LocaleSignInRoute
  LocaleSignUpRoute: typeof LocaleSignUpRoute
  LocaleTasksRoute: typeof LocaleTasksRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAdminPreordersRoute: typeof LocaleAdminPreordersRoute
  LocaleAdminProductsRoute: typeof LocaleAdminProductsRoute
  LocaleAdminServicesRoute: typeof LocaleAdminServicesRoute
  LocaleSignInSsoCallbackRoute: typeof LocaleSignInSsoCallbackRoute
  LocaleSignUpSplatRoute: typeof LocaleSignUpSplatRoute
  LocaleSignUpSsoCallbackRoute: typeof LocaleSignUpSsoCallbackRoute
  LocaleTasksSplatRoute: typeof LocaleTasksSplatRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocalePreorderRoute: LocalePreorderRoute,
  LocaleServicesRoute: LocaleServicesRoute,
  LocaleSignInRoute: LocaleSignInRoute,
  LocaleSignUpRoute: LocaleSignUpRoute,
  LocaleTasksRoute: LocaleTasksRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAdminPreordersRoute: LocaleAdminPreordersRoute,
  LocaleAdminProductsRoute: LocaleAdminProductsRoute,
  LocaleAdminServicesRoute: LocaleAdminServicesRoute,
  LocaleSignInSsoCallbackRoute: LocaleSignInSsoCallbackRoute,
  LocaleSignUpSplatRoute: LocaleSignUpSplatRoute,
  LocaleSignUpSsoCallbackRoute: LocaleSignUpSsoCallbackRoute,
  LocaleTasksSplatRoute: LocaleTasksSplatRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRoute,
  PreorderProductsSplatRoute: PreorderProductsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
